### ISSUE TITLE
WaniKani APIv2 Migration

### ISSUE THREAD

**Issue by turtlemaster19** [Kaniwani/kw-frontend#95]
All the work on KW will be moot, and might as well come up with some way to merge with KameSame, if we can't migrate to APIv2 before the September 1st deadline.

Please respond, @tadgh

**Comment by DJTB** [comment]
Tadgh pretty much handles https://github.com/Kaniwani/kw-backend and has had a V2 branch setup for awhile. I believe he was waiting for it to be finalized because they kept changing it - making any WIP requiring constant updates. Hopefully it doesn't require much work to finalize our side of things.

Frontend is pretty much done in another branch as well (might need some adjustment based on any backend changes): https://github.com/Kaniwani/kw-frontend/tree/add-v2-api

**Comment by turtlemaster19** [comment]
@DJTB Please let me know if I should close this issue. I just wanted to make sure it was addressed and I thought this was the most reasonable place.

**Comment by DJTB** [comment]
It's fine to leave as a reminder and for anyone else that comes along to submit the same issue.

**Comment by tadgh** [comment]
Heyo, V2 has been cut over to as of today. There's an announcement on the homepage. Sorry I never replied, this notification must have slipped through the cracks

**Comment by turtlemaster19** [comment]
@tadgh No problem, thanks for addressing it!
